export const articles = [
  { id:'umbrella', title:'The Blue Umbrella', translation:'蓝色雨伞', level:'初级', minutes:6, icon:'☂', theme:'theme-blue', paragraphs:[['On a rainy afternoon, Lily found a blue umbrella beside the bus stop.','It was clean, and its handle had a little silver star.','Lily looked around, but nobody was there.'],['She carried the umbrella to the small bakery on the corner.','The baker smiled and said, “A girl left it here this morning.”','Just then, a wet girl ran inside. Lily handed her the umbrella.'],['“Thank you!” the girl said.','Lily felt warm, even though the rain was cold.','A small act of kindness can brighten someone’s day.']], translations:['一个下雨的午后，莉莉在公交站旁发现了一把蓝色雨伞。伞很干净，伞柄上还有一颗小小的银色星星。莉莉四处看了看，但周围没有人。','她把伞带到街角的小面包店。面包师笑着说：“一个女孩今天早上把它落在这里了。”就在这时，一个浑身湿透的女孩跑进店里，莉莉把伞递给了她。','“谢谢你！”女孩说道。虽然雨很冷，莉莉心里却暖暖的。一个小小的善举，也能照亮别人的一天。'], words:['kindness','umbrella','beside','handle','carry','corner','hand','brighten'], grammar:['past','although'], questions:[{type:'细节理解',kind:'choice',prompt:'Where did Lily find the umbrella?',cn:'莉莉在哪里发现了这把雨伞？',options:['At the bakery','Beside the bus stop','In her classroom','On the bus'],answer:1,explanation:'文章第一句说明，Lily found the umbrella beside the bus stop。'}, {type:'词义猜测',kind:'choice',prompt:'What does “handed” mean in the story?',cn:'结合语境，文中的 handed 是什么意思？',options:['写下','递给','购买','修理'],answer:1,explanation:'Lily 把伞交给那个女孩，因此 handed 在这里表示“递给”。'}, {type:'推理判断',kind:'choice',prompt:'How did Lily probably feel at the end?',cn:'莉莉最后可能是什么心情？',options:['Proud and warm','Angry and tired','Afraid of the girl','Sorry about the rain'],answer:0,explanation:'原文说 Lily felt warm，说明帮助别人让她感到温暖、开心。'}, {type:'主旨归纳',kind:'choice',prompt:'What is the best title for the story?',cn:'哪一个标题最适合这篇短文？',options:['A Rainy Bus Ride','A Small Act of Kindness','The Silver Star','A Busy Bakery'],answer:1,explanation:'故事围绕 Lily 归还雨伞、帮助陌生女孩展开，表达善意能带来温暖。'}] },
  { id:'seed', title:'A Seed on the Windowsill', translation:'窗台上的一颗种子', level:'初级', minutes:5, icon:'🌱', theme:'theme-green', paragraphs:[['Every morning, Ben opened the window before school.','One day, he saw a tiny seed in a flowerpot.','He did not know who had put it there.'],['Ben gave the seed a little water and placed the pot in the sun.','Days passed, and a small green shoot appeared.','Ben checked it every day and wrote down what changed.'],['After a few weeks, a yellow flower opened.','Ben smiled and showed it to his grandmother.','“Good things grow when we care for them,” she said.']], translations:['每天早晨，上学前本都会打开窗户。一天，他在花盆里看到一颗小小的种子。他不知道是谁把它放在那里。','本给种子浇了一点水，又把花盆放到阳光下。几天过去了，一株绿色的小嫩芽冒了出来。本每天都去看看，并记下它发生的变化。','几周后，一朵黄色的小花开放了。本笑着把花展示给奶奶看。“用心照料，美好的事物就会成长。”奶奶说道。'], words:['seed','tiny','appear','place','shoot','check','change','care'], grammar:['past','when'], questions:[{type:'细节理解',kind:'choice',prompt:'What did Ben see in the flowerpot?',cn:'本在花盆里看到了什么？',options:['A little bird','A tiny seed','A yellow leaf','A small stone'],answer:1,explanation:'第一段写到 he saw a tiny seed in a flowerpot。'}, {type:'推理判断',kind:'choice',prompt:'Why did Ben write down the changes?',cn:'本为什么把变化记下来？',options:['He wanted to care for and observe the seed.','He had to finish his homework.','His grandmother asked him to sell it.','He wanted to water the window.'],answer:0,explanation:'他每天查看种子的变化并记录，说明他在持续观察、照料它。'}, {type:'主旨归纳',kind:'choice',prompt:'What can we learn from the story?',cn:'我们能从故事中了解到什么？',options:['Plants grow without water.','Care and patience help good things grow.','Windows should stay closed.','Flowers bloom in one day.'],answer:1,explanation:'Ben 持续照顾种子，最后它开出了花，体现了耐心和关爱的重要性。'}] }
]

export const words = [
 {word:'kindness',ipa:'/ˈkaɪndnəs/',pos:'n.',meaning:'善意；友好',frequency:'高频词',note:'kindness 指友善、体贴他人的行为或品质。常用 a small act of kindness 表示“一次小小的善举”。',forms:'kind adj. 友善的；kindly adv. 友善地',memory:'kind（友善的）+ -ness（名词后缀）→ kindness（友善；善意）。',examples:[{en:'A small act of kindness can brighten someone’s day.',cn:'一个小小的善举也能照亮别人的一天。'},{en:'Thank you for your kindness.',cn:'谢谢你的好意。'}]},
 {word:'umbrella',ipa:'/ʌmˈbrelə/',pos:'n.',meaning:'雨伞；伞',frequency:'常用词',note:'可数名词，表示遮雨或遮阳用的伞。注意拼写中间有双写的 l。',forms:'复数 umbrellas',memory:'联想：下雨天记得带 umbrella。',examples:[{en:'She opened her umbrella in the rain.',cn:'她在雨中撑开了雨伞。'}]},
 {word:'beside',ipa:'/bɪˈsaɪd/',pos:'prep.',meaning:'在……旁边',frequency:'常用词',note:'表示位置关系，后面接名词或代词。不要与 besides（此外）混淆。',forms:'beside the bus stop 在公交站旁',memory:'side 是“边”，be-side 可联想为“在……边上”。',examples:[{en:'The shop is beside the station.',cn:'商店在车站旁边。'}]},
 {word:'handle',ipa:'/ˈhændl/',pos:'n.',meaning:'把手；柄',frequency:'常用词',note:'在 umbrella handle 中表示伞柄；也可以作动词，表示“处理；应付”。',forms:'handles; handled（动词过去式）',memory:'门把手、杯柄、伞柄都可以叫 handle。',examples:[{en:'The cup has a small handle.',cn:'这个杯子有一个小把手。'}]},
 {word:'carry',ipa:'/ˈkæri/',pos:'v.',meaning:'拿；搬；携带',frequency:'常用词',note:'强调把某物从一处带到另一处。过去式 carried。',forms:'carries; carried; carrying',memory:'carry sth. to somewhere：把某物带到某处。',examples:[{en:'He carried the box to the kitchen.',cn:'他把盒子搬到了厨房。'}]},
 {word:'corner',ipa:'/ˈkɔːrnər/',pos:'n.',meaning:'拐角；角落',frequency:'常用词',note:'on the corner 常表示“在拐角处”；in the corner 表示“在角落里”。',forms:'on the corner of the street 在街道拐角处',memory:'街角的小店：a shop on the corner。',examples:[{en:'There is a bakery on the corner.',cn:'拐角处有一家面包店。'}]},
 {word:'hand',ipa:'/hænd/',pos:'v.',meaning:'递；交给',frequency:'常用词',note:'作动词表示把东西递给某人，常用 hand sth. to sb. 或 hand sb. sth.。',forms:'hands; handed; handing',memory:'hand someone a book：递给某人一本书。',examples:[{en:'She handed the keys to her brother.',cn:'她把钥匙递给了弟弟。'}]},
 {word:'brighten',ipa:'/ˈbraɪtn/',pos:'v.',meaning:'使明亮；使开心',frequency:'常用词',note:'brighten someone’s day 是常见表达，意为“让某人开心起来；使某人一天愉快”。',forms:'bright adj. 明亮的；brightness n. 明亮',memory:'bright（明亮的）+ -en（使……）→ brighten（使明亮）。',examples:[{en:'Your message brightened my day.',cn:'你的消息让我这一天都开心起来。'}]},
 {word:'seed',ipa:'/siːd/',pos:'n.',meaning:'种子',frequency:'常用词',note:'可数名词；plant a seed 表示“播种”。',forms:'复数 seeds',memory:'A seed can grow into a plant. 种子可以长成植物。',examples:[{en:'The seed needs water and sunlight.',cn:'这颗种子需要水和阳光。'}]}
]

export const grammar = [
 {title:'一般过去时：讲述过去发生的事',summary:'发现、寻找与故事叙述',level:'基础语法',explanation:'描述过去某个时间发生并结束的动作，常与 yesterday、one day、last week 等时间表达连用。规则动词通常加 -ed；不规则动词需要单独记忆。',pattern:'主语 + 动词过去式 + 其他',examples:[{en:'Lily found a blue umbrella.',cn:'莉莉发现了一把蓝色雨伞。'},{en:'Ben gave the seed some water.',cn:'本给种子浇了些水。'}],quiz:{prompt:'选择正确的动词形式：Yesterday, Lily ___ the umbrella.',options:['find','finds','found','finding'],answer:2,explanation:'Yesterday 表示过去时间，find 的过去式是不规则变化 found。'}},
 {title:'Although 引导让步状语从句',summary:'表达“虽然……但是……”',level:'进阶语法',explanation:'although 引导让步状语从句，说明某种情况存在，但主句结果与预期不同。although 和 but 通常不在同一个句子中同时使用。',pattern:'Although + 主语 + 谓语，主语 + 谓语',examples:[{en:'Although the rain was cold, Lily felt warm.',cn:'虽然雨很冷，莉莉心里却很温暖。'}],quiz:{prompt:'选择正确的连接词：___ it was raining, they went outside.',options:['Although','Because','So','Or'],answer:0,explanation:'句意是“虽然在下雨，他们还是出去了”，需要 although 表示让步。'}},
 {title:'When 引导时间状语从句',summary:'描述某个时间发生的动作',level:'基础语法',explanation:'when 可以引导时间状语从句，表示“当……时”。讲述过去发生的事时，主句和从句中的动词通常都使用过去时。',pattern:'When + 一般过去时，主语 + 一般过去时',examples:[{en:'When the girl came in, Lily handed her the umbrella.',cn:'女孩进来时，莉莉把雨伞递给了她。'}],quiz:{prompt:'When Ben ___ the flower, he smiled.',options:['see','saw','sees','seeing'],answer:1,explanation:'故事发生在过去，see 的过去式是 saw。'}}
]
